# Simulation settings for using moveit_sim_controllers
moveit_sim_hw_interface:
  joint_model_group: custom_arm
  joint_model_group_pose: home
# Settings for ros_control_boilerplate control loop
generic_hw_control_loop:
  loop_hz: 300
  cycle_time_error_threshold: 0.01
# Settings for ros_control hardware interface
hardware_interface:
  joints:
    - One_joint
    - Two_joint
    - Three_joint
    - Four_joint
  sim_control_mode: 1  # 0: position, 1: velocity
# Publish all joint states
# Creates the /joint_states topic necessary in ROS
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50
controller_list:
  - name: arm_position_controller
    action_ns: position_controllers
    default: True
    type: JointPositionController
    joints:
      - One_joint
      - Two_joint
      - Three_joint
      - Four_joint
    gains:
    One_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    Two_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    Three_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    Four_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1