controller_manager_ns: /
controller_list:
  - name: /pos_based_pos_traj_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: true
    joints:
      - One_joint
      - Two_joint
      - Three_joint
      - Four_joint